doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            string_functions:
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
                DAY: DoctrineExtensions\Query\Mysql\Day
        mappings:
            # SHARED
            shared_value_object:
                is_bundle: false
                type: xml
                dir: '%kernel.root_dir%/Shared/Infrastructure/Persistence/Doctrine/embeddable'
                prefix: 'Overseer\Shared\Domain\ValueObject'
            shared_message_bus:
                is_bundle: false
                type: xml
                dir: '%kernel.root_dir%/Shared/Infrastructure/Persistence/Doctrine/entity'
                prefix: 'Overseer\Shared\Infrastructure\Bus\Event'

            # USER
            user_entity:
                is_bundle: false
                type: xml
                dir: '%kernel.root_dir%/User/Infrastructure/Persistence/Doctrine/entity'
                prefix: 'Overseer\User\Domain\Entity'

            user_value_object:
                is_bundle: false
                type: xml
                dir: '%kernel.root_dir%/User/Infrastructure/Persistence/Doctrine/embeddable'
                prefix: 'Overseer\User\Domain\ValueObject'

            user_enums:
                is_bundle: false
                type: xml
                dir: '%kernel.root_dir%/User/Infrastructure/Persistence/Doctrine/enum'
                prefix: 'Overseer\User\Domain\Enum'

            # PROJECT
            project_entity:
                is_bundle: false
                type: xml
                dir: '%kernel.root_dir%/Project/Infrastructure/Persistence/Doctrine/entity'
                prefix: 'Overseer\Project\Domain\Entity'

            project_value_object:
                is_bundle: false
                type: xml
                dir: '%kernel.root_dir%/Project/Infrastructure/Persistence/Doctrine/embeddable'
                prefix: 'Overseer\Project\Domain\ValueObject'

            project_enums:
                is_bundle: false
                type: xml
                dir: '%kernel.root_dir%/Project/Infrastructure/Persistence/Doctrine/enum'
                prefix: 'Overseer\Project\Domain\Enum'