jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            user_dto:
                namespace_prefix: "Overseer\\User\\Domain\\Dto"
                path: "%kernel.root_dir%/User/Application/config/serializer/dto"

            project_dto:
                namespace_prefix: "Overseer\\Project\\Domain\\Dto"
                path: "%kernel.root_dir%/Project/Application/config/serializer/dto"

