api_v1_project_post:
    path: /api/v1/project
    methods: ['POST']
    controller: Overseer\Project\Infrastructure\Http\Action\CreateProject

api_v1_project_member_invitation_post:
    path: /api/v1/project/{_project_uuid}/project-member-invitation
    methods: ['POST']
    controller: Overseer\Project\Infrastructure\Http\Action\InviteNewMember

api_v1_project_member_invitation_accept:
    path: /api/v1/project/{_project_uuid}/project-member-invitation/{_invitation_uuid}/accept
    methods: ['PUT']
    controller: Overseer\Project\Infrastructure\Http\Action\AcceptInvitation

api_v1_project_member_invitation_decline:
    path: /api/v1/project/{_project_uuid}/project-member-invitation/{_invitation_uuid}/decline
    methods: ['PUT']
    controller: Overseer\Project\Infrastructure\Http\Action\DeclineInvitation

api_v1_project_member_delete:
    path: /api/v1/project/{_project_uuid}/project-member/{_project_member_uuid}
    methods: ['DELETE']
    controller: Overseer\Project\Infrastructure\Http\Action\RemoveProjectMember

api_v1_project_member_invitation_cancel:
    path: /api/v1/project/{_project_uuid}/project-member-invitation/{_invitation_uuid}
    methods: ['DELETE']
    controller: Overseer\Project\Infrastructure\Http\Action\CancelInvitation

api_v1_projects:
    path: /api/v1/project
    methods: ['GET']
    controller: Overseer\Project\Infrastructure\Http\Action\GetProjects

api_v1_create_api_key:
    path: /api/v1/project/{_project_id}/api-key
    methods: ['POST']
    controller: Overseer\Project\Infrastructure\Http\Action\CreateApiKeyAction

api_v1_remove_api_key:
    path: /api/v1/project/{_project_id}/api-key/{_api_key_id}
    methods: ['DELETE']
    controller: Overseer\Project\Infrastructure\Http\Action\RemoveApiKeyAction