api_v1_project_post:
    path: /api/v1/project
    methods: ['POST']
    controller: Overseer\Project\Infrastructure\Http\Action\CreateProjectAction

api_v1_project_member_invitation_post:
    path: /api/v1/project/{_project_id}/project-member-invitation
    methods: ['POST']
    controller: Overseer\Project\Infrastructure\Http\Action\InviteNewProjectMemberAction

api_v1_project_member_invitation_accept:
    path: /api/v1/project/{_project_id}/project-member-invitation/{_invitation_id}/accept
    methods: ['PUT']
    controller: Overseer\Project\Infrastructure\Http\Action\AcceptInvitationAction

api_v1_project_member_invitation_decline:
    path: /api/v1/project/{_project_id}/project-member-invitation/{_invitation_id}/decline
    methods: ['PUT']
    controller: Overseer\Project\Infrastructure\Http\Action\DeclineInvitationAction

api_v1_project_member_delete:
    path: /api/v1/project/{_project_id}/project-member/{_project_member_id}
    methods: ['DELETE']
    controller: Overseer\Project\Infrastructure\Http\Action\RemoveProjectMemberAction

api_v1_project_member_invitation_cancel:
    path: /api/v1/project/{_project_id}/project-member-invitation/{_invitation_id}
    methods: ['DELETE']
    controller: Overseer\Project\Infrastructure\Http\Action\CancelInvitationAction

api_v1_projects:
    path: /api/v1/project
    methods: ['GET']
    controller: Overseer\Project\Infrastructure\Http\Action\GetProjectsAction

api_v1_create_api_key:
    path: /api/v1/project/{_project_id}/api-key
    methods: ['POST']
    controller: Overseer\Project\Infrastructure\Http\Action\CreateApiKeyAction

api_v1_remove_api_key:
    path: /api/v1/project/{_project_id}/api-key/{_api_key_id}
    methods: ['DELETE']
    controller: Overseer\Project\Infrastructure\Http\Action\RemoveApiKeyAction

api_v1_project:
    path: /api/v1/project/{_project_id}
    methods: ['GET']
    controller: Overseer\Project\Infrastructure\Http\Action\GetProjectAction