services:
    _defaults:
        autowire: false
        autoconfigure: true

    Overseer\Ping: ~


# Use command_handler tag for a CommandHandler
# Use domain_events_subscriber tag for EventSubscriber
# Use query_handler tag for QueryHandler